language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
        - platform-tool
        - tool
        - android-22
        - build-tools-22.0.1
        - extra-android-m2repository
        - extra-google-m2repository

    # The BuildTools version used by your project
    # - build-tools-22.0.1

    # The SDK version used to compile your project
    # - android-22
    
before_install:
 - chmod +x gradlew
