language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-android-support
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-22
    
before_install:
 - chmod +x gradlew
